sudo: required
services:
  - docker

before_install: 
  - docker build -t cervinka/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cervinka/react-test npm test

after_success:
  - docker build -t cervinka/multi-client ./client
  - docker build -t cervinka/multi-nginx ./nginx
  - docker build -t cervinka/multi-server ./server
  - docker build -t cervinka/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push cervinka/multi-client
  - docker push cervinka/multi-nginx
  - docker push cervinka/multi-server
  - docker push cervinka/multi-worker